import type { Metadata } from 'next';
import { Inter, Manrope } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/global/Navbar';

// const inter = Inter({ subsets: ["latin"] });
const manrope = Manrope({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Rastro Ai',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`mx-auto p-5 md:p-10 ${manrope.className}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
